# Generated by Django 5.1.1 on 2024-09-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
    ]
